/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.Shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuyerAddItemToCartCommand
 */
export interface BuyerAddItemToCartCommand {
    /**
     * 
     * @type {string}
     * @memberof BuyerAddItemToCartCommand
     */
    customerNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuyerAddItemToCartCommand
     */
    sessionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BuyerAddItemToCartCommand
     */
    productCatalogueNumber?: string | null;
}

export function BuyerAddItemToCartCommandFromJSON(json: any): BuyerAddItemToCartCommand {
    return BuyerAddItemToCartCommandFromJSONTyped(json, false);
}

export function BuyerAddItemToCartCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuyerAddItemToCartCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerNumber': !exists(json, 'customerNumber') ? undefined : json['customerNumber'],
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
        'productCatalogueNumber': !exists(json, 'productCatalogueNumber') ? undefined : json['productCatalogueNumber'],
    };
}

export function BuyerAddItemToCartCommandToJSON(value?: BuyerAddItemToCartCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customerNumber': value.customerNumber,
        'sessionId': value.sessionId,
        'productCatalogueNumber': value.productCatalogueNumber,
    };
}

