/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.Shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductInfo,
    ProductInfoFromJSON,
    ProductInfoFromJSONTyped,
    ProductInfoToJSON,
} from './ProductInfo';

/**
 * 
 * @export
 * @interface CartEntry
 */
export interface CartEntry {
    /**
     * 
     * @type {ProductInfo}
     * @memberof CartEntry
     */
    productInfo?: ProductInfo;
    /**
     * 
     * @type {number}
     * @memberof CartEntry
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof CartEntry
     */
    quantity?: number;
}

export function CartEntryFromJSON(json: any): CartEntry {
    return CartEntryFromJSONTyped(json, false);
}

export function CartEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartEntry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productInfo': !exists(json, 'productInfo') ? undefined : ProductInfoFromJSON(json['productInfo']),
        'price': !exists(json, 'price') ? undefined : json['price'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function CartEntryToJSON(value?: CartEntry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productInfo': ProductInfoToJSON(value.productInfo),
        'price': value.price,
        'quantity': value.quantity,
    };
}

