/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.Shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderCreateCommand
 */
export interface OrderCreateCommand {
    /**
     * 
     * @type {string}
     * @memberof OrderCreateCommand
     */
    customerNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderCreateCommand
     */
    sessionId?: string | null;
}

export function OrderCreateCommandFromJSON(json: any): OrderCreateCommand {
    return OrderCreateCommandFromJSONTyped(json, false);
}

export function OrderCreateCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderCreateCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerNumber': !exists(json, 'customerNumber') ? undefined : json['customerNumber'],
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
    };
}

export function OrderCreateCommandToJSON(value?: OrderCreateCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'customerNumber': value.customerNumber,
        'sessionId': value.sessionId,
    };
}

