/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.Shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductInfo
 */
export interface ProductInfo {
    /**
     * 
     * @type {string}
     * @memberof ProductInfo
     */
    catalogueNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductInfo
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductInfo
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductInfo
     */
    price?: number;
}

export function ProductInfoFromJSON(json: any): ProductInfo {
    return ProductInfoFromJSONTyped(json, false);
}

export function ProductInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'catalogueNumber': !exists(json, 'catalogueNumber') ? undefined : json['catalogueNumber'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
    };
}

export function ProductInfoToJSON(value?: ProductInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'catalogueNumber': value.catalogueNumber,
        'name': value.name,
        'description': value.description,
        'price': value.price,
    };
}

