/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.Shopping
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShippingInformation
 */
export interface ShippingInformation {
    /**
     * 
     * @type {number}
     * @memberof ShippingInformation
     */
    countryCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ShippingInformation
     */
    fullName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingInformation
     */
    streetAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingInformation
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingInformation
     */
    stateProvince?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingInformation
     */
    postcode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShippingInformation
     */
    phoneNumber?: string | null;
}

export function ShippingInformationFromJSON(json: any): ShippingInformation {
    return ShippingInformationFromJSONTyped(json, false);
}

export function ShippingInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShippingInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'countryCode': !exists(json, 'countryCode') ? undefined : json['countryCode'],
        'fullName': !exists(json, 'fullName') ? undefined : json['fullName'],
        'streetAddress': !exists(json, 'streetAddress') ? undefined : json['streetAddress'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'stateProvince': !exists(json, 'stateProvince') ? undefined : json['stateProvince'],
        'postcode': !exists(json, 'postcode') ? undefined : json['postcode'],
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
    };
}

export function ShippingInformationToJSON(value?: ShippingInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'countryCode': value.countryCode,
        'fullName': value.fullName,
        'streetAddress': value.streetAddress,
        'city': value.city,
        'stateProvince': value.stateProvince,
        'postcode': value.postcode,
        'phoneNumber': value.phoneNumber,
    };
}

