/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.CatalogueManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductApiModel
 */
export interface ProductApiModel {
    /**
     * 
     * @type {string}
     * @memberof ProductApiModel
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductApiModel
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductApiModel
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProductApiModel
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductApiModel
     */
    price?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductApiModel
     */
    available?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductApiModel
     */
    description?: string | null;
}

export function ProductApiModelFromJSON(json: any): ProductApiModel {
    return ProductApiModelFromJSONTyped(json, false);
}

export function ProductApiModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductApiModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'available': !exists(json, 'available') ? undefined : json['available'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ProductApiModelToJSON(value?: ProductApiModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
        'name': value.name,
        'price': value.price,
        'available': value.available,
        'description': value.description,
    };
}

