/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.CatalogueManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductApiModel,
    ProductApiModelFromJSON,
    ProductApiModelFromJSONTyped,
    ProductApiModelToJSON,
} from './ProductApiModel';

/**
 * 
 * @export
 * @interface ProductUpdateCommand
 */
export interface ProductUpdateCommand {
    /**
     * 
     * @type {ProductApiModel}
     * @memberof ProductUpdateCommand
     */
    product?: ProductApiModel;
}

export function ProductUpdateCommandFromJSON(json: any): ProductUpdateCommand {
    return ProductUpdateCommandFromJSONTyped(json, false);
}

export function ProductUpdateCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdateCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'product': !exists(json, 'product') ? undefined : ProductApiModelFromJSON(json['product']),
    };
}

export function ProductUpdateCommandToJSON(value?: ProductUpdateCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product': ProductApiModelToJSON(value.product),
    };
}

