// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Store.Catalogue.Infrastructure.EntityFramework;

namespace Store.Catalogue.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(StoreCatalogueDbContext))]
    [Migration("20211101144432_project_display_initial")]
    partial class project_display_initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Store.Catalogue.Domain.Product.Projections.ProductDisplay.ProductDisplay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Serialized")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.HasKey("Id");

                    b.ToTable("product_display");
                });
#pragma warning restore 612, 618
        }
    }
}
