/* tslint:disable */
/* eslint-disable */
/**
 * Store.Api.Payments
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentCreateCommand
 */
export interface PaymentCreateCommand {
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateCommand
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateCommand
     */
    source?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentCreateCommand
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreateCommand
     */
    note?: string | null;
}

export function PaymentCreateCommandFromJSON(json: any): PaymentCreateCommand {
    return PaymentCreateCommandFromJSONTyped(json, false);
}

export function PaymentCreateCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCreateCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': !exists(json, 'orderId') ? undefined : json['orderId'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'note': !exists(json, 'note') ? undefined : json['note'],
    };
}

export function PaymentCreateCommandToJSON(value?: PaymentCreateCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'orderId': value.orderId,
        'source': value.source,
        'amount': value.amount,
        'note': value.note,
    };
}

